version: '3'

services:

  db_server:
    restart: on-failure
    image: amacharla/aa-db
    deploy:
      replicas: 2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
    networks:
      - aa-backend
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app_server:
    restart: on-failure
    deploy:
      replicas: 2
    image: amacharla/aa-app
    links:
      - web_server
      - db_server
    networks:
      - aa-backend
    volumes:
      - web_app:/web_app
    ports:
      - "5001:5001"

  web_server:
    restart: on-failure
    deploy:
      replicas: 3
    image: amacharla/aa-web
    networks:
      - aa-backend
    volumes:
      - ./web_app/static:/usr/share/nginx/html
    ports:
      - "80:80"

networks:
  aa-backend:
          
volumes:
  mysql_data:
    driver: "cloudstor:aws"
  web_app:
    driver: "cloudstor:aws"
